const MONSTER_LIST = [
  "Aboleth",
  "Acolyte (NPC)",
  "Adult Black Dragon (Chromatic)",
  "Adult Blue Dragon (Chromatic)",
  "Adult Brass Dragon (Metallic)",
  "Adult Bronze Dragon (Metallic)",
  "Adult Copper Dragon (Metallic)",
  "Adult Gold Dragon (Metallic)",
  "Adult Green Dragon (Chromatic)",
  "Adult Red Dragon (Chromatic)",
  "Adult Silver Dragon (Metallic)",
  "Adult White Dragon (Chromatic)",
  "Air Elemental",
  "Ancient Black Dragon (Chromatic)",
  "Ancient Blue Dragon (Chromatic)",
  "Ancient Brass Dragon (Metallic)",
  "Ancient Bronze Dragon (Metallic)",
  "Ancient Copper Dragon (Metallic)",
  "Ancient Gold Dragon (Metallic)",
  "Ancient Green Dragon (Chromatic)",
  "Ancient Red Dragon (Chromatic)",
  "Ancient Silver Dragon (Metallic)",
  "Ancient White Dragon (Chromatic)",
  "Androsphinx (Sphinx)",
  "Animated Armor (Animated Object)",
  "Ankheg",
  "Ape (Creature)",
  "Archmage (NPC)",
  "Assassin (NPC)",
  "Awakened Shrub (Creature)",
  "Awakened Tree (Creature)",
  "Axe Beak (Creature)",
  "Azer",
  "Baboon (Creature)",
  "Badger (Creature)",
  "Balor (Demon)",
  "Bandit (NPC)",
  "Bandit Captain (NPC)",
  "Barbed Devil (Devil)",
  "Basilisk",
  "Bat (Creature)",
  "Bearded Devil (Devil)",
  "Behir",
  "Berserker (NPC)",
  "Black Bear (Creature)",
  "Black Pudding (Ooze)",
  "Blink Dog (Creature)",
  "Blood Hawk (Creature)",
  "Boar (Creature)",
  "Bone Devil (Devil)",
  "Brown Bear (Creature)",
  "Bugbear",
  "Bulette",
  "Camel (Creature)",
  "Cat (Creature)",
  "Centaur",
  "Chain Devil (Devil)",
  "Chimera",
  "Chuul",
  "Clay Golem",
  "Cloaker",
  "Cloud Giant (Giant)",
  "Cockatrice",
  "Commoner (NPC)",
  "Constrictor Snake (Creature)",
  "Couatl",
  "Crab (Creature)",
  "Crocodile (Creature)",
  "Cult Fanatic (NPC)",
  "Cultist (NPC)",
  "Customizing NPCs (NPC)",
  "Darkmantle",
  "Death Dog (Creature)",
  "Deer (Creature)",
  "Deva (Angel)",
  "Dire Wolf (Creature)",
  "Djinni (Genie)",
  "Doppelganger",
  "Draft Horse (Creature)",
  "Dragon Turtle",
  "Dretch (Demon)",
  "Drider",
  "Druid (NPC)",
  "Dryad",
  "Duergar",
  "Dust Mephit",
  "Eagle (Creature)",
  "Earth Elemental",
  "Efreeti (Genie)",
  "Elephant (Creature)",
  "Elf, Drow",
  "Elk (Creature)",
  "Erinyes (Devil)",
  "Ettercap",
  "Ettin",
  "Fire Elemental",
  "Fire Giant (Giant)",
  "Flesh Golem",
  "Flying Snake (Creature)",
  "Flying Sword (Animated Object)",
  "Frog (Creature)",
  "Frost Giant (Giant)",
  "Gargoyle",
  "Gelatinous Cube (Ooze)",
  "Ghast (Ghoul)",
  "Ghost",
  "Ghoul",
  "Giant Ape (Creature)",
  "Giant Badger (Creature)",
  "Giant Bat (Creature)",
  "Giant Boar (Creature)",
  "Giant Centipede (Creature)",
  "Giant Constrictor Snake (Creature)",
  "Giant Crab (Creature)",
  "Giant Crocodile (Creature)",
  "Giant Eagle (Creature)",
  "Giant Elk (Creature)",
  "Giant Fire Beetle (Creature)",
  "Giant Frog (Creature)",
  "Giant Goat (Creature)",
  "Giant Hyena (Creature)",
  "Giant Lizard (Creature)",
  "Giant Octopus (Creature)",
  "Giant Owl (Creature)",
  "Giant Poisonous Snake (Creature)",
  "Giant Rat (Creature)",
  "Giant Scorpion (Creature)",
  "Giant Sea Horse (Creature)",
  "Giant Shark (Creature)",
  "Giant Spider (Creature)",
  "Giant Toad (Creature)",
  "Giant Vulture (Creature)",
  "Giant Wasp (Creature)",
  "Giant Weasel (Creature)",
  "Giant Wolf Spider (Creature)",
  "Gibbering Mouther",
  "Glabrezu (Demon)",
  "Gladiator (NPC)",
  "Gnoll",
  "Gnome, Deep (Svirfneblin)",
  "Goat (Creature)",
  "Goblin",
  "Gorgon",
  "Gray Ooze",
  "Green Hag",
  "Grick",
  "Griffon",
  "Grimlock",
  "Guard (NPC)",
  "Guardian Naga",
  "Gynosphinx (Sphinx)",
  "Half-Dragon Template",
  "Harpy",
  "Hawk (Creature)",
  "Hell Hound",
  "Hezrou (Demon)",
  "Hill Giant (Giant)",
  "Hippogriff",
  "Hobgoblin",
  "Homunculus",
  "Horned Devil",
  "Hunter Shark (Creature)",
  "Hydra",
  "Hyena (Creature)",
  "Ice Devil (Devil)",
  "Ice Mephit",
  "Imp (Devil)",
  "Invisible Stalker",
  "Iron Golem",
  "Jackal (Creature)",
  "Killer Whale (Creature)",
  "Knight (NPC)",
  "Kobold",
  "Kraken",
  "Lamia",
  "Lemure (Devil)",
  "Lich",
  "Lion (Creature)",
  "Lizard (Creature)",
  "Lizardfolk",
  "Mage (NPC)",
  "Magma Mephit",
  "Magmin",
  "Mammoth (Creature)",
  "Manticore",
  "Marilith (Demon)",
  "Mastiff (Creature)",
  "Medusa",
  "Merfolk",
  "Merrow",
  "Mimic",
  "Minotaur Skeleton",
  "Minotaur",
  "Mule (Creature)",
  "Mummy Lord",
  "Mummy",
  "Nalfeshnee (Demon)",
  "Night Hag",
  "Nightmare",
  "Noble (NPC)",
  "Ochre Jelly (Ooze)",
  "Octopus (Creature)",
  "Ogre Zombie",
  "Ogre",
  "Oni",
  "Orc",
  "Otyugh",
  "Owl (Creature)",
  "Owlbear",
  "Panther (Creature)",
  "Pegasus",
  "Phase Spider (Creature)",
  "Pit Fiend (Devil)",
  "Planetar (Angel)",
  "Plesiosaurus (Dinosaur)",
  "Poisonous Snake (Creature)",
  "Polar Bear (Creature)",
  "Pony (Creature)",
  "Priest (NPC)",
  "Pseudodragon",
  "Purple Worm",
  "Quasit (Demon)",
  "Quipper (Creature)",
  "Rakshasa",
  "Rat (Creature)",
  "Raven (Creature)",
  "Reef Shark (Creature)",
  "Remorhaz",
  "Rhinoceros (Creature)",
  "Riding Horse (Creature)",
  "Roc",
  "Roper",
  "Rug of Smothering (Animated Object)",
  "Rust Monster",
  "Saber-Toothed Tiger (Creature)",
  "Sahuagin",
  "Salamander",
  "Sample",
  "Satyr",
  "Scorpion (Creature)",
  "Scout (NPC)",
  "Sea Hag",
  "Sea Horse (Creature)",
  "Shadow",
  "Shambling Mound",
  "Shield Guardian",
  "Shrieker (Fungi)",
  "Skeleton",
  "Solar (Angel)",
  "Specter",
  "Spider (Creature)",
  "Spirit Naga",
  "Sprite",
  "Spy (NPC)",
  "Steam Mephit",
  "Stirge",
  "Stone Giant (Giant)",
  "Stone Golem",
  "Storm Giant (Giant)",
  "Succubus-Incubus",
  "Swarm of Bats (Creature)",
  "Swarm of Insects (Creature)",
  "Swarm of Poisonous Snakes (Creature)",
  "Swarm of Quippers (Creature)",
  "Swarm of Rats (Creature)",
  "Swarm of Ravens (Creature)",
  "Tarrasque",
  "Thug (NPC)",
  "Tiger (Creature)",
  "Treant",
  "Tribal Warrior (NPC)",
  "Triceratops (Dinosaur)",
  "Troll",
  "Tyrannosaurus Rex (Dinosaur)",
  "Unicorn",
  "Vampire Spawn",
  "Vampire",
  "Veteran (NPC)",
  "Violet Fungus (Fungi)",
  "Vrock (Demon)",
  "Vulture (Creature)",
  "Warhorse (Creature)",
  "Warhorse Skeleton",
  "Water Elemental",
  "Weasel (Creature)",
  "Werebear (Lycanthrope)",
  "Wereboar (Lycanthrope)",
  "Wererat (Lycanthrope)",
  "Weretiger (Lycanthrope)",
  "Werewolf (Lycanthrope)",
  "Wight",
  "Will-o'-Wisp",
  "Winter Wolf (Creature)",
  "Wolf (Creature)",
  "Worg (Creature)",
  "Wraith",
  "Wyrmling Black Dragon (Chromatic)",
  "Wyrmling Blue Dragon (Chromatic)",
  "Wyrmling Brass Dragon (Metallic)",
  "Wyrmling Bronze Dragon (Metallic)",
  "Wyrmling Copper Dragon (Metallic)",
  "Wyrmling Gold Dragon (Metallic)",
  "Wyrmling Green Dragon (Chromatic)",
  "Wyrmling Red Dragon (Chromatic)",
  "Wyrmling Silver Dragon (Metallic)",
  "Wyrmling White Dragon (Chromatic)",
  "Wyvern",
  "Xorn",
  "Young Black Dragon (Chromatic)",
  "Young Blue Dragon (Chromatic)",
  "Young Brass Dragon (Metallic)",
  "Young Bronze Dragon (Metallic)",
  "Young Copper Dragon (Metallic)",
  "Young Gold Dragon (Metallic)",
  "Young Green Dragon (Chromatic)",
  "Young Red Dragon (Chromatic)",
  "Young Silver Dragon (Metallic)",
  "Young White Dragon (Chromatic)",
  "Zombie"
];
